/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import UmbLogo2Image from 'src/assets/images/UmbLogo_UMB_logo.png';
import { styled } from '@mui/material/styles';
import { UmbLogoProps } from 'src/types';

const UmbLogo1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `36px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const UmbLogo2: any = styled('img')({
  height: `36px`,
  width: `150px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

function UmbLogo(props: UmbLogoProps): JSX.Element {
  return (
    <UmbLogo1 className={props.className}>
      <UmbLogo2 src={UmbLogo2Image} loading="lazy" alt={'UMB-logo'} />
    </UmbLogo1>
  );
}

export default UmbLogo;
